from create_page import create_row

def main():
    ''' 
    Homework database pages structure

    -- Property's name -> Property's type -> Values for property --

    created -> created_time -> an autogenerated date
    status -> select -> Completed, In progress, Completed
    assign -> person -> Toto Rios
    type -> multi-select -> Investigation, Project, Activity, to deliver
    priority -> select -> High, normal, low
    due date -> date -> a date
    materia -> relation -> subject
    
    -- Content of page, composed by four main blocks 
    Instructions - If there's any, the script shall put it in here
    Personal comments - Any unnoficial instruction given by professor
    Attachments - Space to create homework
    Resources - If there's any, the script shall put it in here
    
----------------------------------------------------------------------------------
    Subject database pages structure
    
    -- Property's name -> Property's type -> Values for property --
    
    created -> created_time -> an autogenerated date
    profesor -> relation -> professor
    grade -> select -> third, fourth, fifth, etc..
    
    -- Content of page, composed by five main blocks
    Announcements - Personal announcements
    Notes - A database with pages for my notes, sort by asc creation date
    Homework - A relational database with the main, showing only pages for current subject and set to board view 
    Resources - If there's any, added by my own
    Grading criteria - Added by my own'''

    database_id = '438e5ef3-19e8-4e31-9ba6-d2eda2899ea8'

    data = create_row(database_id)
    if data is not None:
        # print(json.dumps(data, indent=4))
        print('New row available here: {}'.format(data['url']))


if __name__ == '__main__':
    main()